POST https://neuqmtn8ed.execute-api.eu-west-1.amazonaws.com/prod/all-mpnet-base-v2
Content-Type: application/json

{
  "texts": ["One flame-winged brought a white-winged harp-player Even where my lady and I lay all alone; Saying: ‘Behold this minstrel is unknown; Bid him depart, for I am minstrel here: Only my songs are to love's dear ones dear.’ Then said I ‘Through thine hautboy's rapturous tone Unto my lady still this harp makes moan, And still she deems the cadence deep and clear.’ Then said my lady: ‘Thou art passion of Love, And this Love's worship: both he plights to me. Thy mastering music walks the sunlit sea: But where wan water trembles in the grove, And the wan moon is all the light thereof, This harp still makes my name its voluntary.’"]
}

###

POST https://neuqmtn8ed.execute-api.eu-west-1.amazonaws.com/prod/msmarco-distilbert-cos-v5-model
Content-Type: application/json

{
  "texts": ["One flame-winged brought a white-winged harp-player Even where my lady and I lay all alone; Saying: ‘Behold this minstrel is unknown; Bid him depart, for I am minstrel here: Only my songs are to love's dear ones dear.’ Then said I ‘Through thine hautboy's rapturous tone Unto my lady still this harp makes moan, And still she deems the cadence deep and clear.’ Then said my lady: ‘Thou art passion of Love, And this Love's worship: both he plights to me. Thy mastering music walks the sunlit sea: But where wan water trembles in the grove, And the wan moon is all the light thereof, This harp still makes my name its voluntary.’"]
}

###

POST https://neuqmtn8ed.execute-api.eu-west-1.amazonaws.com/prod/multi-qa-distilbert-cos-v1
Content-Type: application/json

{
  "texts": ["One flame-winged brought a white-winged harp-player Even where my lady and I lay all alone; Saying: ‘Behold this minstrel is unknown; Bid him depart, for I am minstrel here: Only my songs are to love's dear ones dear.’ Then said I ‘Through thine hautboy's rapturous tone Unto my lady still this harp makes moan, And still she deems the cadence deep and clear.’ Then said my lady: ‘Thou art passion of Love, And this Love's worship: both he plights to me. Thy mastering music walks the sunlit sea: But where wan water trembles in the grove, And the wan moon is all the light thereof, This harp still makes my name its voluntary.’"]
}

###

POST https://neuqmtn8ed.execute-api.eu-west-1.amazonaws.com/prod/multi-qa-MiniLM-L6-cos-v1
Content-Type: application/json

{
  "texts": ["One flame-winged brought a white-winged harp-player Even where my lady and I lay all alone; Saying: ‘Behold this minstrel is unknown; Bid him depart, for I am minstrel here: Only my songs are to love's dear ones dear.’ Then said I ‘Through thine hautboy's rapturous tone Unto my lady still this harp makes moan, And still she deems the cadence deep and clear.’ Then said my lady: ‘Thou art passion of Love, And this Love's worship: both he plights to me. Thy mastering music walks the sunlit sea: But where wan water trembles in the grove, And the wan moon is all the light thereof, This harp still makes my name its voluntary.’"]
}

###

POST https://neuqmtn8ed.execute-api.eu-west-1.amazonaws.com/prod/multi-qa-mpnet-base-cos-v1
Content-Type: application/json

{
  "texts": ["One flame-winged brought a white-winged harp-player Even where my lady and I lay all alone; Saying: ‘Behold this minstrel is unknown; Bid him depart, for I am minstrel here: Only my songs are to love's dear ones dear.’ Then said I ‘Through thine hautboy's rapturous tone Unto my lady still this harp makes moan, And still she deems the cadence deep and clear.’ Then said my lady: ‘Thou art passion of Love, And this Love's worship: both he plights to me. Thy mastering music walks the sunlit sea: But where wan water trembles in the grove, And the wan moon is all the light thereof, This harp still makes my name its voluntary.’"]
}

###

POST https://neuqmtn8ed.execute-api.eu-west-1.amazonaws.com/prod/multi-qa-mpnet-base-dot-v1
Content-Type: application/json

{
  "texts": ["One flame-winged brought a white-winged harp-player Even where my lady and I lay all alone; Saying: ‘Behold this minstrel is unknown; Bid him depart, for I am minstrel here: Only my songs are to love's dear ones dear.’ Then said I ‘Through thine hautboy's rapturous tone Unto my lady still this harp makes moan, And still she deems the cadence deep and clear.’ Then said my lady: ‘Thou art passion of Love, And this Love's worship: both he plights to me. Thy mastering music walks the sunlit sea: But where wan water trembles in the grove, And the wan moon is all the light thereof, This harp still makes my name its voluntary.’"]
}

###
